[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://serene-heliotrope-3138a4.netlify.app/api/:splat"