import express from "express";
import { createTask, deleteTaskById, getTaskById, getTasks, updateTaskById } from "../controllers/taskController";
import { validateTask } from "../middlewares/validateTask";
import { authMiddleware } from "../middlewares/authMiddleware";
const router = express.Router();
router.post("/", authMiddleware, validateTask, createTask);
router.get("/", authMiddleware, getTasks);
router.get("/:id", authMiddleware, getTaskById);
router.put("/:id", authMiddleware, validateTask, updateTaskById);
router.delete("/:id", authMiddleware, deleteTaskById);
export default router;