import express from "express";
import { createTask, deleteTaskById, getTaskById, getTasks, updateTaskById } from "../controllers/taskController";
import { validateTask } from "../middlewares/validateTask";
import { authMiddleware } from "../middlewares/authMiddleware";
const router = express.Router();
router.post("/", authMiddleware, validateTask, createTask);
router.get("/", authMiddleware, getTasks);
router.get("/:id",getTaskById);
router.put("/:id",validateTask,updateTaskById);
router.delete("/:id",deleteTaskById);
export default router;